### ISSUE TITLE
PerformanceNavigationTiming marked as unrecognized

### ISSUE THREAD

**Issue by awoehrl** [snowplow/chrome-snowplow-inspector#81]
Hi!

This is a really weird bug I think. PerformanceNavigationTiming gets marked as unrecognized, even though the schema is available on Iglucentral and the extension has it in the registry overview:

Unrecognized inside events:
![image](https://github.com/snowplow/chrome-snowplow-inspector/assets/44875496/0787e0b0-fe10-4079-8c2e-49723975ddde)

Screenshot of the registry:
![image](https://github.com/snowplow/chrome-snowplow-inspector/assets/44875496/44314f04-d23d-45d6-a7d3-1aaefaef58ff)

**Comment by miike** [comment]
Thanks for flagging this - indeed an odd one as `PerformanceTiming` resolves fine but not `PerformanceNavigationTiming`. We'll have a look!

**Comment by jethron** [comment]
Thanks @awoehrl ! This was an issue with how that schema uses `$ref` to reference a definition for the serverTiming object within the schema; this isn't very common on Iglu Central so wasn't set up to work properly yet. It should work as expected in v0.3.7
